{% set name = "libsoup" %}
{% set version = "2.74.2" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: f0a427656e5fe19e1df71c107e88dfa1b2e673c25c547b7823b6018b40d01159

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - gobject-introspection
    # for native build prior to cross build
    - gettext     # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - sqlite      # [build_platform != target_platform]
    - libxml2     # [build_platform != target_platform]
    - brotli      # [build_platform != target_platform]
    - libpsl      # [build_platform != target_platform]
    - glib-networking  # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - glib
    - sqlite
    - libxml2
    - brotli
    - libpsl
    - glib-networking
    - zlib
  run:
    - sqlite
    - glib-networking
    - glib
    - libxml2
    - brotli
    - libpsl
    - zlib
    - gettext

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config
    - pygobject
  commands:
    - test -f ${PREFIX}/include/libsoup-2.4/libsoup/soup.h                   # [unix]
    - test -f ${PREFIX}/lib/libsoup-2.4.dylib                                # [osx]
    - test -f ${PREFIX}/lib/libsoup-2.4.so                                   # [linux]
    - test -f ${PREFIX}/lib/girepository-1.0/Soup-2.4.typelib                # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libsoup-2.4.pc                         # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libsoup-2.4.pc exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\girepository-1.0\\Soup-2.4.typelib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libsoup-2.4\\libsoup\\soup.h exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\soup-2.4-1.dll exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\\soup-2.4.lib exit 1                        # [win]

about:
  home: https://gitlab.gnome.org/GNOME/libsoup
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: HTTP client/server library for GNOME

extra:
  recipe-maintainers:
    - tschoonj
