{% set name = "libsoup" %}
{% set version = "3.4.4" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 291c67725f36ed90ea43efff25064b69c5a2d1981488477c05c481a3b4b0c5aa

build:
  number: 1
  # skipping Windows builds until there is a Windows build of nghttp2
  skip: true  # [win]
  run_exports:
    # Seems to have excellent forward compatibility in the 2.x series
    # https://abi-laboratory.pro/index.php?view=timeline&l=libsoup
    - {{ pin_subpackage('libsoup', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - gobject-introspection
    # for native build prior to cross build
    - gettext     # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - sqlite      # [build_platform != target_platform]
    - libxml2     # [build_platform != target_platform]
    - libnghttp2  # [build_platform != target_platform]
    - brotli      # [build_platform != target_platform]
    - libpsl      # [build_platform != target_platform]
    - glib-networking  # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - glib
    - sqlite
    - libxml2
    - brotli
    - libnghttp2
    - libpsl
    - glib-networking
    - zlib
  run:
    # Needs run export
    # https://github.com/conda-forge/glib-networking-feedstock/pull/28
    - glib-networking
    # https://github.com/conda-forge/libpsl-feedstock/issues/11
    - libpsl

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config
    - pygobject
  commands:
    - test -f ${PREFIX}/include/libsoup-3.0/libsoup/soup.h                   # [unix]
    - test -f ${PREFIX}/lib/libsoup-3.0.dylib                                # [osx]
    - test -f ${PREFIX}/lib/libsoup-3.0.so                                   # [linux]
    - test -f ${PREFIX}/lib/girepository-1.0/Soup-3.0.typelib                # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libsoup-3.0.pc                         # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libsoup-3.0.pc exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\girepository-1.0\\Soup-3.0.typelib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libsoup-3.0\\libsoup\\soup.h exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\soup-3.0-1.dll exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\\soup-3.0.lib exit 1                        # [win]

about:
  home: https://gitlab.gnome.org/GNOME/libsoup
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: HTTP client/server library for GNOME

extra:
  recipe-maintainers:
    - tschoonj
